version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
    restart: always
#app.js code

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    restart: always

  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./websocket:/usr/src/app
    restart: always
